services:
  - type: web
    name: cv-proxy
    rootDir: proxy
    env: node
    plan: free
    buildCommand: pnpm i && pnpm build || pnpm i
    startCommand: pnpm dev
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ALLOW_ORIGINS
        value: https://dmt4000.github.io, http://localhost:5173, http://localhost:5176

