name: Deploy app to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm i
      - name: Build cv-app for Pages
        working-directory: app
        env:
          BASE_PATH: /cv1/
          VITE_PROXY_URL: ${{ vars.VITE_PROXY_URL }}
        run: pnpm build && pnpm postbuild
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: { path: app/dist }
  deploy:
    needs: build
    permissions: { pages: write, id-token: write }
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4


